package dbService.executor;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Executor class
 *
 * This class provides methods to execute SQL queries and updates on a database connection.
 *
 * @author razlivinsky
 * @since 21.03.2024
 */
public class Executor {
    private final Connection connection;

    /**
     * Instantiates a new Executor with the provided database connection.
     *
     * @param connection the database connection to be used for executing queries and updates
     */
    public Executor(Connection connection) {
        this.connection = connection;
    }

    /**
     * Executes an SQL update operation on the database.
     *
     * @param update the SQL update statement to be executed
     * @throws SQLException if a database access error occurs or the SQL execution fails
     */
    public void execUpdate(String update) throws SQLException {
        Statement stmt = connection.createStatement();
        stmt.execute(update);
        stmt.close();
    }

    /**
     * Executes an SQL query and returns the result set.
     *
     * @param query the SQL query to be executed
     * @return the result set generated by the query
     * @throws SQLException if a database access error occurs or the SQL execution fails
     */
    public ResultSet execQuery(String query) throws SQLException {
        Statement stmt = connection.createStatement();
        stmt.execute(query);
        return stmt.getResultSet();
    }
}